language: cpp
os:
  - osx

before_install:
  - brew update
  - brew install flex
  - brew install bison
  - brew link bison --force

script: make && make test
compiler:
  - clang
  - gcc
# Handle git submodules yourself
git:
  submodules: false
  # Use sed to replace the SSH URL with the public URL, then initialize submodules
  before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
